#!/usr/bin/env ruby

require 'mail'
require 'optparse'
require 'pathname'

mail = Mail.new do
  to 'jblackman'
  from 'jblackman'
  subject 'Convert: please'
  body 'Please convert these files'
  add_file 'test1.doc'
  add_file 'poem1.jpg'
end

outmode = ''

OptionParser.new do |opts|
  opts.on( '-m', '--mode MODE', ['dir','rts','email','summary'], 'Output mode of streamer' ) do |mode|
    case mode
      when 'dir'
        mkdir 'foo'
        outmode = '-d foo'
      when 'rts'
        outmode = '-r'
      when 'email'
        outmode = '-e jblackman'
    end
  end
  opts.on( '-h' , '--help', 'This message' ) { puts opts; exit }
end.parse!

BASE=Pathname.new(__FILE__).realpath.parent.parent

IO::popen( "#{BASE + 'bin' + 'heathen_mailstream'} #{outmode} -v", 'w' ) do |f|
  f.write mail.to_s
end
