#!/usr/bin/env ruby
#
# This script is used for development testing of the bin/autoheathen script. It
# constructs a sample email message and pipes it into autoheathen for
# processing
#
# Usage: test_autoheathen -h (run this for the opts)
#

require 'mail'
require 'optparse'
require 'pathname'

outmode = ''
email_addr = `/usr/bin/whoami`
email_file = nil

OptionParser.new do |opts|
  opts.on( '-m', '--mode MODE', ['dir','rts','email','summary'], 'Output mode of streamer' ) do |mode|
    case mode
      when 'dir'
        mkdir 'foo'
        outmode = '-d foo'
      when 'rts'
        outmode = '-r'
      when 'email'
        outmode = "-e #{email_addr}"
    end
  end
  opts.on( '-w', '--write-email FILE', 'Don\'t run the test, just generate the email and write it to file for later use' ) { |f| email_file = f }
  opts.on( '-h' , '--help', 'This message' ) { puts opts; exit }
end.parse!

mail = Mail.new do
  to email_addr
  from email_addr
  subject 'Convert: please'
  body 'Please convert these files'
  add_file 'support/test1.doc'
  add_file 'support/poem1.jpg'
end

BASE=Pathname.new(__FILE__).realpath.parent.parent

if email_file
  File.open(email_file, 'w') do |f|
    f.write mail.to_s
  end
  puts "Created email file #{email_file}"
else
  IO::popen( "#{BASE + 'bin' + 'autoheathen'} #{outmode} -v", 'w' ) do |f|
    f.write mail.to_s
  end
end
